version: '3'

services:
  sads_container: 
    image: postgres:14.3
    container_name: sads_container
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - ${PORT_DB}:${PORT_DB}
volumes:
  postgres:
    driver: local